dist: trusty
sudo: required
language: node_js
node_js:
  - "8"
cache:
  directories:
  - "node_modules"
addons:
  firefox: latest
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable fluxbox
  postgresql: "9.6"
branches:
  only: "master"
beforeInstall:
   - "export DISPLAY=:99.0"
   # starts Virtual X-Frame Buffer (xvfb)
   - "sh -e /etc/init.d/xvfb start"
   - fluxbox >/dev/null 2>&1 &
