language: node_js
node_js:
  - "8"
cache:
  directories:
  - "node_modules"
addons:
  postgresql: "9.6"
branches:
  only: "master"
beforeInstall:
   - "export CHROME_BIN=chromium-browser"
   - "export DISPLAY=:99.0"
   # starts Virtual X-Frame Buffer (xvfb)
   - "sh -e /etc/init.d/xvfb start"
